name: VCMI Mods

on:
  push:
    branches:
      - develop
  pull_request:
    paths:
      - "**.json"
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  validate_json:
    if: ${{ github.event_name == 'pull_request' || github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Python environment
        run: sudo apt update && sudo apt install -y python3 python3-pip
      - name: Install jstyleson
        run: pip3 install jstyleson
      - name: Validate json
        run: python3 .github/validate_json.py

  validate_mod_json:
    if: ${{ github.event_name == 'pull_request' || github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' }}
    needs: validate_json
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v3
      - name: Install jstyleson
        run: pip3 install jstyleson
      - name: Validate mod json
        run: python3 .github/validate_mod_json.py

  update_size_stars:
    if: ${{ (github.event_name == 'push' && github.ref == 'refs/heads/develop') || github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install jstyleson
        run: pip3 install jstyleson

      - name: Update size
        run: python3 .github/update_size.py

      - name: Update stars
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python3 .github/update_stars.py

      - name: Update descriptions
        run: python3 .github/update_descriptions.py

      - name: Update screenshots
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python3 .github/update_screenshots.py

      - name: Determine branch and switch
        id: branch_info
        run: |
          branch_name=$(git symbolic-ref --short HEAD)
          echo "branch_name=$branch_name" >> $GITHUB_ENV
          echo "Checked out branch: $branch_name"

      - name: Set upstream for branch
        run: git push --set-upstream origin $branch_name

      - name: Commit changes to the correct branch
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: Update sizes, stars, descriptions and screenshots
          add: '*.json'
          push: --force
